extern class Variant {}
extern class VariantType {}
extern class VariantOperator {}
extern class NodePath {}
extern class GArray {}
extern class PoolStringArray {}
extern class PoolByteArray {}
extern class PoolVector2Array {}
extern class PoolVector3Array {}
extern class PoolColorArray {}
extern class PoolIntArray {}
extern class PoolRealArray {}
extern class Dictionary {}
extern class Error {}
extern class RID {}
extern class Transform {}
extern class Transform2D {}
extern class Vector2 {}
extern class Vector3 {}
extern class Vector3Axis {}
extern class Quat {}
extern class Plane {}
extern class Basis {}
extern class Rect2 {}
extern class AABB {}
extern class Color {}
